### ISSUE TITLE
Correct way to create TsdFrame with pynajax?

### ISSUE THREAD

**Issue by rly** [pynapple-org/pynajax#25]
I am using pynapple in a project and want to use the pynajax backend. It works fine for everything, but I get a warning when trying to create a TsdFrame. Am I doing something wrong? Should I convert my data to a jax.ndarray before creating a TsdFrame?

```python
import pynapple as nap
import numpy as np
nap.nap_config.set_backend("jax")
x = nap.TsdFrame(
    t=np.arange(10),
    d=np.random.rand(10, 5),
    columns=["a", "b", "c", "d", "e"],
)
```

Output:
```
[/Users/rly/mambaforge/envs/mec/lib/python3.12/site-packages/pynajax/utils.py:126](http://localhost:8888/Users/rly/mambaforge/envs/mec/lib/python3.12/site-packages/pynajax/utils.py#line=125): UserWarning: Converting 'd' to jax.ndarray. The provided array was of type 'ndarray'.
  return cast_to_jax(array, array_name, suppress_conversion_warnings)
```

**Comment by gviejo** [comment]
No it's good. It's an internal pynapple warning.

**Comment by gviejo** [comment]
Yuo can toggle warnings like described here : https://pynapple-org.github.io/pynapple/reference/core/config/#pynapple.core.config.PynappleConfig.suppress_conversion_warnings

**Comment by rly** [comment]
Got it. Thanks!
